name: Deploy Static Website with Terraform

on:
  push:
    branches:
      - main  # Substitua pela sua branch principal

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Verifique sua versão

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BLOG_DOMAIN: ${{ secrets.BLOG_DOMAIN }}
        acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
        ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BLOG_DOMAIN: ${{ secrets.BLOG_DOMAIN }}
        acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
        ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID }}
